### ISSUE TITLE
Counterfactual "predictions" feature request

### ISSUE THREAD

**Issue by spinkney** [helske/walker#10]
Thanks for the update to allowing NAs. I'm running some models where I'm interested in what would have happened if my covariates had taken on different values in the past. I'm OK with assuming that everything else would have been the same except for the effect of the covariates. I've resorted to adding in an extra data parameter (`counterfact_xreg_rw`) in the data block and `y_counterfact[N]` in generated quantities: 

```
  // replicated data from posterior predictive distribution
  for(t in 1:n) {
    y_counterfact[t] = xbeta[t] + dot_product(counterfact_xreg_rw[, t] * beta_rw[, t]);
    y_fit[t] = xbeta[t] + dot_product(xreg_rw[, t], beta_rw[, t]);
    y_rep[t] = normal_rng(y_fit[t], gamma_y[t] * sigma_y);
  }
```

I'm wondering if this could be included in the `predict` function with an optional parameter pass to indicate that this is for counterfactual predictions during the estimation time period?

**Comment by helske** [comment]
Sorry, missed this. Yes, I could see this being a useful feature. Unfortunately, at the moment I do not have time to work on `walker` but pull requests are of course very welcome.

**Comment by helske** [comment]
There is now a new function called `predict_counterfactual` which is similar to `predict` function but which can be used to predict past observations with new covariate values.
