### ISSUE TITLE
add argument to plot_predict to allow user to control plotting of predictions on link vs. response scale

### ISSUE THREAD

**Issue by wpetry** [helske/walker#12]
Opening separate issue following discussion in #11...

### problem
The `predict.walker_fit` method returns values on both the link and response scales for models with non-Gaussian errors. `plot_predict` plots both, and this is not currently controllable by the user. This behavior is particularly problematic for `distribution='logit'` with high numbers of trials `u`. In these cases, the response scale is so much higher than the link scale (constrained between [0,1]) that variation on the link scale is completely flattened.

### workaround
As a temporary workaround, `ggedit::remove_geom()` can be used to remove the undesired set of predictions. For an example of use, see the first post in #11.

### feature request
This issue requests that an argument be added to `plot_predict` that allows users to specify whether they want the posterior predictions plotted on the 'link' or 'response' scale. I advocate setting 'link' as the default, as this corresponds to the state that is usually of interest when doing state space modeling. This default would also mirror the behavior of well-known packages like `lme4` (see `?predict.merMod`).

**Comment by helske** [comment]
I now added a new option for the `type` argument of the `predict` function. Earlier you could return the estimates on the scale of the response variable (number of success for binomial and number of cases for Poisson)  or on the mean level (probability of success for the binomial and expected number of cases for Poisson), depending on the argument `type`. Now for completeness, there is also a third option `link` i.e. estimates before using the inverse-link function. 

More importantly, `plot_predict` now contains argument `draw_obs` which can be set to `response`, `mean`, or `none`, with default value chosen based on the input.

**Comment by helske** [comment]
This is now available in CRAN version as well.
