### ISSUE TITLE
test fails with Stan 2.16.x

### ISSUE THREAD

**Issue by bgoodri** [helske/walker#4]
The unit test "stan side works" in tests.R is not working for me. Those double precision numbers you are testing against depend on the operating system, the compiler, and the version of Stan. So, I would instead just test that the output contains a valid `stanfit` object.

**Comment by helske** [comment]
Thanks, I forgot to add large enough tolerances for the tests, but yeah it might be simpler and sufficient to just test type and structure of the output.

**Comment by helske** [comment]
This is now fixed, I do more precise testing of the output only locally now.
