### ISSUE TITLE
Error running example for walker_glm

### ISSUE THREAD

**Issue by sean-horvath** [helske/walker#7]
I get the following errors when I try to run the example code for walker_glm.  The same error occurs for both examples and when I try to use my own data.

> data("discoveries", package = "datasets")
> out <- walker_glm(discoveries ~ -1 + 
+                       rw2(~ 1, beta_prior = c(0, 10), sigma_prior = c(0, 2), slope_prior = c(0, 2)), 
+                   distribution = "poisson", iter = 1000, chains = 1, refresh = 0)
[1] "Error in sampler$call_sampler(args_list[[i]]) : "                                                                                         
[2] "  Exception: assign: Rows of left-hand-side (100) and rows of right-hand-side (2) must match in size  (in 'model_walker_glm' at line 325)"
[1] "error occurred during calling the sampler; sampling not done"

**Comment by helske** [comment]
Thanks, will look into this tomorrow. Looks like missing transpose issue somewhere.

**Comment by helske** [comment]
Ok, I though I fixed this issue in november, but hadn't rebuilt the package properly, so even though the model source code showed the changes, rstan generated `models.hpp` contained wrong index validation of internal matrix Rt. Weird. And I never uploaded the package to CRAN... Should work now if you install from github (`devtools::install_github("helske/walker)`. Will update to CRAN now as well.
