### ISSUE TITLE
Stan License Includes. Apache 2 dependency is being considered for Stan Math.

### ISSUE THREAD

**Issue by breckbaldwin** [helske/walker#8]
Hi,
    Walker apparently depends on Stan which is New BSD licensed but we are likely to add a dependency on an Apache 2 lib. This impacts GPL2 licensed projects. The voting thread is at https://discourse.mc-stan.org/t/apache-2-library-inclusion-into-stan-math-general-policy-case-trip-wire-consensus-decision/10929

   We are seeking comments up until midnight Sept 14th anywhere on the planet.

**Comment by helske** [comment]
Thanks, I don't mind changing the licence of walker to GPL3.
